fixtures:
    symlinks:
      local_security_policy: "#{source_dir}"
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: 4.6.0
      hieradata:
        repo: 'git@gitlab.com:singlestone/hieradata.git'
    forge_modules:
